---
- include_role:
    name: k3s

- include_role:
    name: dt-operator
  vars:
    operator_mode: "classicFullStack"  
    dt_operator_release: "v1.4.0"
    log_monitoring: "oneagent"
    cluster_name: power_dashboarding

- include_role:
    name: app-easytrade

#- include_role:
#    name: monaco

#- name: Install Monaco
#  include_role:
#    name: monaco-v2

#- include_role:
#    name: app-easytrade
#    tasks_from: apply-dt-configuration

- include_role:
    name: dashboard
