---
- include_role:
    name: microk8s

- include_role:
    name: dt-operator

- name: Install Monaco
  include_role:
    name: monaco-v2

- include_role:
    name: monaco

- include_role:
    name: app-easytrade
  vars:
    manifest_strategy: "static" # static or fetch_latest: static will use the static files from the app-easytrade role, dynamic will clone the EasyTrade repository with the latest files. Attention: This would break the existing deployments if the EasyTrade repository is updated.

- include_role:
    name: app-easytrade
    tasks_from: apply-dt-configuration

- include_role:
    name: dashboard